name: Backup Firestore

on:
  schedule:
    - cron:  '0 0 * * *'

env:
  PROJECT_ID: my-website-33003
  BUCKET: gs://my-website-33003.appspot.com/
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_DB_KEY }}
        export_default_credentials: true
    - run: gcloud info
    - run: gcloud config set project $PROJECT_ID
    - run: gcloud firestore export $BUCKET
